### ISSUE TITLE
Hidden checkboxes

### ISSUE THREAD

**Issue by shaneonabike** [dettogatto/elementor-super-cat#16]
Hey there,

Just a tiny little issue whereby if I select no checkbox I noticed that you output `width:0` on the `cat-checkbox-icon-container` container. It will still automatically generate the padding for that element since you kept hte display:inline-block. You actually need to set it to display:none rather than a width so it won't render any spacing thus making the elements flush.

**Comment by shaneonabike** [comment]
I'll try to generate a patch in the next day or so

**Comment by dettogatto** [comment]
That was on purpose, so you can indent the elements as you want with the "spacing" slider...

**Comment by dettogatto** [comment]
I set the width of the icon container because different icons can have different widths, resulting in misaligned labels. With last commit I made the icons show independently, so you can have, for example, a check-mark when selected and nothing when not, keeping alignment intact. So I'm not changing this behaviour :)
